version: 0.2

phases:
  install:
    runtime-versions:
      python: latest
    commands:
      - echo "Installing dependencies..."
      - pip install -r software.txt -t lib
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip lambda_function.py
  post_build:
    commands:
      - echo "No post build"
      - echo "DONE!!"


artifacts:
   files:
      - deployment_package.zip
      - template.yaml
